#!/usr/bin/env bash
# Export contract ABIs and addresses from contracts/ → frontend/.
# Run from anywhere; paths are absolute relative to repo root.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONTRACTS_DIR="$ROOT/contracts"
FRONTEND_DIR="$ROOT/frontend"
ABIS_DIR="$FRONTEND_DIR/lib/abis"
OUT_TS="$FRONTEND_DIR/lib/contracts.ts"

CONTRACTS=(AgentRegistry AgentAccountFactory BondVault SlashVerifier AgentPaymaster ReputationHook)

echo "→ forge build"
( cd "$CONTRACTS_DIR" && forge build --silent )

mkdir -p "$ABIS_DIR"

echo "→ extracting ABIs"
for name in "${CONTRACTS[@]}"; do
  src="$CONTRACTS_DIR/out/${name}.sol/${name}.json"
  dst="$ABIS_DIR/${name}.json"
  [[ -f "$src" ]] || { echo "missing artifact: $src"; exit 1; }
  python3 -c "import json,sys; print(json.dumps(json.load(open('$src'))['abi'], indent=2))" > "$dst"
  echo "   $dst"
done

echo "→ generating $OUT_TS from $CONTRACTS_DIR/.env"
python3 - "$CONTRACTS_DIR/.env" "$OUT_TS" <<'PY'
import os, sys, re

env_path, out_path = sys.argv[1], sys.argv[2]
env = {}
with open(env_path) as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line: continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip().strip('"').strip("'")

KEYS = [
    ("agentRegistry",      "AGENT_REGISTRY"),
    ("agentAccountFactory","AGENT_ACCOUNT_FACTORY"),
    ("bondVault",          "BOND_VAULT"),
    ("slashVerifier",      "SLASH_VERIFIER"),
    ("agentPaymaster",     "AGENT_PAYMASTER"),
    ("reputationHook",     "REPUTATION_HOOK"),
]

def block(label):
    lines = ["    {"] if False else []
    out = []
    for ts_key, env_key in KEYS:
        addr = env.get(env_key, "")
        out.append(f'    {ts_key}: "{addr}" as `0x${{string}}`,')
    return "\n".join(out)

contents = f'''// AUTO-GENERATED by scripts/export-abis.sh — do not edit by hand.
// Re-run the script after every contract deploy.

export const CONTRACTS = {{
  31337: {{
{block("31337")}
  }},
  11155111: {{
    agentRegistry: "" as `0x${{string}}`,
    agentAccountFactory: "" as `0x${{string}}`,
    bondVault: "" as `0x${{string}}`,
    slashVerifier: "" as `0x${{string}}`,
    agentPaymaster: "" as `0x${{string}}`,
    reputationHook: "" as `0x${{string}}`,
  }},
}} as const;

export type SupportedChainId = keyof typeof CONTRACTS;

export function getContracts(chainId: number) {{
  return CONTRACTS[chainId as SupportedChainId] ?? null;
}}
'''

with open(out_path, "w") as f:
    f.write(contents)
print(f"   {out_path}")
PY

echo "✓ export complete"
