// AUTO-GENERATED by scripts/export-abis.sh — do not edit by hand.
// Re-run the script after every contract deploy.

export const CONTRACTS = {
  31337: {
    agentRegistry: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9" as `0x${string}`,
    agentAccountFactory: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6" as `0x${string}`,
    bondVault: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9" as `0x${string}`,
    slashVerifier: "0x0165878A594ca255338adfa4d48449f69242Eb8F" as `0x${string}`,
    agentPaymaster: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853" as `0x${string}`,
    reputationHook: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707" as `0x${string}`,
  },
  11155111: {
    agentRegistry: "" as `0x${string}`,
    agentAccountFactory: "" as `0x${string}`,
    bondVault: "" as `0x${string}`,
    slashVerifier: "" as `0x${string}`,
    agentPaymaster: "" as `0x${string}`,
    reputationHook: "" as `0x${string}`,
  },
} as const;

export type SupportedChainId = keyof typeof CONTRACTS;

export function getContracts(chainId: number) {
  return CONTRACTS[chainId as SupportedChainId] ?? null;
}
